#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("MonoAndroidDemo.Resource", IsApplication=true)]

namespace MonoAndroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f040000
			public const int aspect = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int zoom_styles = 2130968577;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int area = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int arrow = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bar = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int bar3D = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int barjoin = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bezier = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int box = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bubble = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int calendar = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int candle = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int circulargauge = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int clock = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int colorgrid = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int contour = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int darvas = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int donut = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int error = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int errorbar = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int errorpoint = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int fastline = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int funnel = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int gantt = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int highlow = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int histogram = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int horizarea = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int horizbar = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int horizbox = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int horizhistogram = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int horizline = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int Icon = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int isosurface = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int kagi = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int knobgauge = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int line = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int lineargauge = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int linepoint = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int logo57x57 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int map = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int numericgauge = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int orgseries = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int pie = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int pointfigure = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int points = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int points3D = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int polar = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int polarbar = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int PolarGrid = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int pyramid = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int radar = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int renko = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int shape = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int smith = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int surface = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int tagcloud = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ternary = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int tower = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int vector3D = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int verticallineargauge = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int volume = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int volumepipe = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int waterfall = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int windrose = 2130837565;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060000
			public const int cb3D = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int imageView1 = 2131099651;
			
			// aapt resource value: 0x7f060004
			public const int linearLayout1 = 2131099652;
			
			// aapt resource value: 0x7f060006
			public const int seriesListView = 2131099654;
			
			// aapt resource value: 0x7f060002
			public const int spinnerZoomStyle = 2131099650;
			
			// aapt resource value: 0x7f060005
			public const int textView1 = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int textView2 = 2131099649;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Editor = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int ListItem = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int Aspect = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050003
			public const int Zoom_Style = 2131034115;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
